from __future__ import annotations

import asyncio
import random
from collections.abc import Awaitable, Callable
from decimal import Decimal
from typing import Any

from .binance_rest import BinanceRestClient
from .config import Settings
from .journal import OrderJournal
from .intents import EntryIntent
from .locking import SingleInstanceLock
from .market_data import MarketDataService
from .observability import AlertManager, configure_logging
from .risk_control import RiskGovernor
from .risk_control import utc_day_start_ms
from .rules import decimal_value
from .trading import TradingService
from .user_stream import RECONCILE_EVENTS, stream_user_events


def _ordinary_role(order: dict[str, Any]) -> str:
    return "CLOSE" if order.get("reduceOnly") else "ENTRY"


def _algo_role(order: dict[str, Any]) -> str:
    order_type = order.get("orderType", order.get("type"))
    return "STOP" if order_type == "STOP_MARKET" else "TAKE_PROFIT"


def _is_algo_trade(order: dict[str, Any], existing: dict[str, Any] | None) -> bool:
    """Identify execution reports generated by a conditional Algo order."""
    return bool(
        order.get("si")
        or order.get("st") == "ALGO_CONDITION"
        or (existing and existing.get("family") == "ALGO")
    )


async def run_user_stream_loop(
    client: BinanceRestClient,
    ws_base_url: str,
    reconciler: "AccountReconciler",
    journal: OrderJournal,
    risk: RiskGovernor,
    alerts: AlertManager,
    operation_lock: asyncio.Lock,
    user_stream_ready: asyncio.Event,
    handle_user_event: Callable[[dict[str, Any]], Awaitable[None]],
    *,
    stream_runner: Callable[..., Awaitable[None]] = stream_user_events,
    sleep: Callable[[float], Awaitable[Any]] = asyncio.sleep,
    random_value: Callable[[], float] = random.random,
) -> None:
    """Keep the private stream connected and reconcile before every attempt."""
    delay = 1.0
    while True:
        try:
            async with operation_lock:
                await asyncio.to_thread(reconciler.startup_reconcile)
            journal.set_control(
                "user_stream_healthy", "false", "user stream connecting"
            )

            def on_connected() -> None:
                user_stream_ready.set()
                journal.set_control(
                    "user_stream_healthy",
                    "true",
                    "user stream connected",
                    severity="INFO",
                )

            await stream_runner(
                client,
                ws_base_url,
                handle_user_event,
                on_connected=on_connected,
            )
            user_stream_ready.clear()
            delay = 1.0
        except asyncio.CancelledError:
            user_stream_ready.clear()
            raise
        except Exception as exc:
            user_stream_ready.clear()
            journal.set_control(
                "user_stream_healthy", "false", f"user stream error: {exc}"
            )
            risk.lock_entries(f"user stream disconnected: {exc}")
            alerts.emit(
                "USER_STREAM_RECONNECT",
                "User stream disconnected; REST reconciliation will run before reconnect",
                severity="ERROR",
                payload={"error": str(exc), "delay": delay},
            )
            await sleep(delay + random_value())
            delay = min(delay * 2, 30.0)


class AccountReconciler:
    def __init__(
        self,
        client: BinanceRestClient,
        journal: OrderJournal,
        service: TradingService,
        risk: RiskGovernor,
        alerts: AlertManager,
        symbols: list[str],
        unprotected_action: str,
    ) -> None:
        self.client = client
        self.journal = journal
        self.service = service
        self.risk = risk
        self.alerts = alerts
        self.symbols = sorted({symbol.upper() for symbol in symbols})
        self.unprotected_action = unprotected_action

    def startup_reconcile(self) -> dict[str, Any]:
        self.client.sync_time()
        account = self.client.account()
        self.journal.record_account_snapshot(account)
        results = {
            symbol: self.reconcile_symbol(symbol, recover_history=True)
            for symbol in self.symbols
        }
        self.journal.append_audit(
            "reconciliation", "STARTUP_COMPLETE", payload={"symbols": self.symbols}
        )
        return results

    def handle_event(self, event: dict[str, Any]) -> None:
        event_type = str(event.get("e", "UNKNOWN"))
        self.journal.append_audit(
            "user_stream",
            event_type,
            severity="INFO",
            payload=event,
        )
        symbol: str | None = None
        if event_type == "ORDER_TRADE_UPDATE":
            order = event.get("o", {})
            symbol = order.get("s")
            client_order_id = order.get("c")
            existing = self.journal.order(str(client_order_id)) if client_order_id else None
            is_algo = _is_algo_trade(order, existing)
            existing_type = existing.get("order_type") if existing else None
            normalized = {
                "symbol": symbol,
                "clientOrderId": client_order_id,
                "orderId": order.get("i"),
                "side": order.get("S"),
                "type": existing_type or order.get("o"),
                "orderType": existing_type or order.get("ot") or order.get("o"),
                "status": order.get("X"),
                "origQty": order.get("q"),
                "executedQty": order.get("z"),
                "avgPrice": order.get("ap"),
                "reduceOnly": order.get("R"),
                "updateTime": order.get("T") or event.get("T"),
            }
            if normalized["clientOrderId"]:
                family = "ALGO" if is_algo else "ORDINARY"
                role = (
                    _algo_role(normalized)
                    if is_algo
                    else _ordinary_role(normalized)
                )
                self.journal.record_order(
                    normalized,
                    family=family,
                    role=role,
                )
                self.journal.transition_order(
                    str(normalized["clientOrderId"]),
                    str(normalized["status"]),
                    event_type=str(order.get("x", event_type)),
                    exchange_time=normalized["updateTime"],
                    payload=event,
                    executed_quantity=str(normalized.get("executedQty") or "0"),
                    average_price=str(normalized.get("avgPrice") or "0"),
                )
            if order.get("x") == "TRADE":
                self.journal.record_fill(order)
        elif event_type == "TRADE_LITE":
            trade = event.get("o", event)
            symbol = trade.get("s") or trade.get("symbol")
            if symbol:
                symbol = str(symbol).upper()
            self.journal.record_fill(
                {
                    **trade,
                    "s": symbol,
                    "t": trade.get("t") or trade.get("tradeId"),
                    "c": trade.get("c") or trade.get("clientOrderId"),
                    "i": trade.get("i") or trade.get("orderId"),
                    "S": trade.get("S") or trade.get("side"),
                    "l": trade.get("l") or trade.get("qty") or trade.get("q"),
                    "L": trade.get("L") or trade.get("price") or "0",
                    "T": trade.get("T") or event.get("T") or event.get("E"),
                }
            )
        elif event_type == "ALGO_UPDATE":
            order = event.get("o") or {}
            symbol = order.get("s") or order.get("symbol")
            client_algo_id = order.get("caid") or order.get("clientAlgoId")
            if client_algo_id:
                normalized = {
                    **order,
                    "symbol": symbol,
                    "clientAlgoId": client_algo_id,
                    "algoId": order.get("aid") or order.get("algoId"),
                    "orderType": order.get("o") or order.get("orderType"),
                    "type": order.get("o") or order.get("orderType"),
                    "side": order.get("S") or order.get("side"),
                    "reduceOnly": order.get("R") or order.get("reduceOnly"),
                    "algoStatus": order.get("X") or order.get("algoStatus") or "NEW",
                    "status": order.get("X") or order.get("algoStatus") or "NEW",
                    "quantity": order.get("q") or order.get("quantity") or "0",
                    "executedQty": order.get("aq") or order.get("executedQty") or "0",
                    "avgPrice": order.get("ap") or order.get("avgPrice") or "0",
                    "triggerPrice": order.get("tp") or order.get("triggerPrice"),
                    "updateTime": order.get("tt") or event.get("T") or event.get("E"),
                }
                self.journal.record_order(
                    normalized, family="ALGO", role=_algo_role(normalized)
                )
                self.journal.transition_order(
                    str(client_algo_id),
                    str(normalized["algoStatus"]),
                    event_type=event_type,
                    exchange_time=normalized.get("updateTime"),
                    payload=event,
                    executed_quantity=str(normalized.get("executedQty") or "0"),
                    average_price=str(normalized.get("avgPrice") or "0"),
                )
                self.journal.transition_order(
                    str(client_algo_id),
                    str(normalized["status"]),
                    event_type="ALGO_UPDATE",
                    exchange_time=normalized["updateTime"],
                    payload=event,
                    executed_quantity=str(normalized.get("executedQty") or "0"),
                    average_price=str(normalized.get("avgPrice") or "0"),
                )
        elif event_type.startswith("CONDITIONAL_ORDER"):
            order = event.get("o") or event.get("or") or event.get("a") or {}
            symbol = order.get("s") or order.get("symbol")
            client_algo_id = order.get("c") or order.get("clientAlgoId")
            if client_algo_id:
                normalized = {
                    **order,
                    "symbol": symbol,
                    "clientAlgoId": client_algo_id,
                    "algoId": order.get("i") or order.get("algoId"),
                    "orderType": order.get("o") or order.get("orderType"),
                    "algoStatus": order.get("X") or order.get("algoStatus") or "NEW",
                }
                self.journal.record_order(
                    normalized, family="ALGO", role=_algo_role(normalized)
                )

        if event_type in RECONCILE_EVENTS:
            targets = [symbol] if symbol in self.symbols else self.symbols
            for target in targets:
                self.reconcile_symbol(str(target))

    def reconcile_symbol(
        self, symbol: str, *, recover_history: bool = False
    ) -> dict[str, Any]:
        symbol = symbol.upper()
        positions = [
            position
            for position in self.client.positions(symbol)
            if decimal_value(position.get("positionAmt", "0")) != 0
        ]
        ordinary = self.client.open_orders(symbol)
        algo = self.client.open_algo_orders(symbol)
        for order in ordinary:
            self.journal.record_order(order, family="ORDINARY", role=_ordinary_role(order))
        for order in algo:
            self.journal.record_order(order, family="ALGO", role=_algo_role(order))
        self._recover_missing_order_states(symbol, ordinary, algo)
        recovered_trades = self._recover_trades(symbol) if recover_history else 0

        if not positions:
            cleanup = None
            if ordinary or algo:
                cleanup = self.service.cancel_all(symbol)
                self.alerts.emit(
                    "FLAT_POSITION_ORDER_CLEANUP",
                    "Removed stale orders for a flat position",
                    symbol=symbol,
                    severity="WARNING",
                    payload={"ordinary": len(ordinary), "algo": len(algo)},
                )
            closed_intents = self.journal.close_active_intents(
                symbol, "exchange position is flat"
            )
            return {
                "position": "FLAT",
                "cleanup": cleanup,
                "closedIntents": closed_intents,
                "recoveredTrades": recovered_trades,
            }

        position = positions[0]
        stop_orders = [order for order in algo if _algo_role(order) == "STOP"]
        take_profit_orders = [order for order in algo if _algo_role(order) == "TAKE_PROFIT"]
        if not stop_orders:
            latest = self.journal.latest_active_intent(symbol)
            if latest and latest.get("stop_price"):
                self.alerts.emit(
                    "PROTECTION_RECOVERY",
                    "Recovering missing stop from the latest local intent",
                    symbol=symbol,
                    severity="WARNING",
                )
                self.service.protect_position(
                    symbol,
                    stop_price=Decimal(latest["stop_price"]),
                    take_profit_price=(
                        Decimal(latest["take_profit_price"])
                        if latest.get("take_profit_price")
                        else None
                    ),
                )
            else:
                reason = f"unprotected managed position detected: {symbol}"
                self.risk.lock_entries(reason)
                self.alerts.emit(
                    "UNPROTECTED_POSITION", reason, symbol=symbol, severity="CRITICAL"
                )
                if self.unprotected_action == "close":
                    self.service.close_position(symbol)
                return {"position": position, "status": "UNPROTECTED"}
        else:
            self.service.sync_protection_quantities(symbol)

        mark = decimal_value(self.client.mark_price(symbol)["markPrice"])
        breaches = self.risk.evaluate_open_positions([position], {symbol: mark})
        if breaches:
            self.risk.lock_entries(str(breaches))
            self.alerts.emit(
                "POSITION_RISK_BREACH",
                "Open position breached a hard risk threshold",
                symbol=symbol,
                severity="CRITICAL",
                payload={"breaches": breaches},
            )
        if not take_profit_orders:
            self.alerts.emit(
                "MISSING_TAKE_PROFIT",
                "Position has a stop but no take-profit",
                symbol=symbol,
                severity="WARNING",
            )
        return {
            "position": position,
            "stopOrders": len(stop_orders),
            "takeProfitOrders": len(take_profit_orders),
            "riskBreaches": breaches,
            "recoveredTrades": recovered_trades,
        }

    def _recover_missing_order_states(
        self,
        symbol: str,
        exchange_ordinary: list[dict[str, Any]],
        exchange_algo: list[dict[str, Any]],
    ) -> None:
        open_ids = {
            str(order.get("clientOrderId") or order.get("clientAlgoId"))
            for order in [*exchange_ordinary, *exchange_algo]
        }
        for local in self.journal.active_orders(symbol):
            client_order_id = str(local["client_order_id"])
            if client_order_id in open_ids or local["status"] in {"CREATED", "SUBMITTING"}:
                continue
            try:
                if local["family"] == "ALGO":
                    recovered = self.client.query_algo_order(client_algo_id=client_order_id)
                    status = str(recovered.get("algoStatus", recovered.get("status", "UNKNOWN")))
                    family = "ALGO"
                else:
                    recovered = self.client.query_order(symbol, client_order_id=client_order_id)
                    status = str(recovered.get("status", "UNKNOWN"))
                    family = "ORDINARY"
                self.journal.record_order(
                    recovered,
                    family=family,
                    role=str(local["role"]),
                    intent_id=local.get("intent_id"),
                )
                self.journal.transition_order(
                    client_order_id,
                    status,
                    event_type="REST_RECONCILIATION",
                    exchange_time=recovered.get("updateTime"),
                    payload=recovered,
                    executed_quantity=str(recovered.get("executedQty", "0")),
                    average_price=str(recovered.get("avgPrice", "0")),
                )
            except Exception as exc:
                self.alerts.emit(
                    "ORDER_RECONCILIATION_FAILED",
                    "Could not determine a local non-terminal order's exchange state",
                    symbol=symbol,
                    severity="ERROR",
                    payload={"client_order_id": client_order_id, "error": str(exc)},
                )

    def _recover_trades(self, symbol: str) -> int:
        trades = self.client.account_trades(symbol, start_time=utc_day_start_ms())
        for trade in trades:
            self.journal.record_fill(trade)
        return len(trades)


class TradingDaemon:
    def __init__(self, settings: Settings, symbols: list[str], interval: str = "1m") -> None:
        self.settings = settings
        self.symbols = symbols
        self.interval = interval

    async def run(self) -> None:
        lock = SingleInstanceLock(self.settings.lock_path)
        lock.acquire()
        journal = OrderJournal(self.settings.database_path)
        client = BinanceRestClient(self.settings)
        logger = configure_logging(self.settings.log_path)
        alerts = AlertManager(journal, logger)
        risk = RiskGovernor(self.settings.risk, journal)
        service = TradingService(client, journal, risk)
        reconciler = AccountReconciler(
            client,
            journal,
            service,
            risk,
            alerts,
            self.symbols,
            self.settings.unprotected_action,
        )
        market = MarketDataService(client, journal, self.settings.ws_url)
        operation_lock = asyncio.Lock()
        user_stream_ready = asyncio.Event()

        async def handle_user_event(event: dict[str, Any]) -> None:
            async with operation_lock:
                await asyncio.to_thread(reconciler.handle_event, event)

        async def user_loop() -> None:
            await run_user_stream_loop(
                client,
                self.settings.ws_url,
                reconciler,
                journal,
                risk,
                alerts,
                operation_lock,
                user_stream_ready,
                handle_user_event,
            )

        async def command_loop() -> None:
            while True:
                commands = await asyncio.to_thread(journal.pending_commands)
                for command in commands:
                    if command["command_type"] == "ENTRY_INTENT" and not user_stream_ready.is_set():
                        continue
                    command_id = int(command["id"])
                    if not journal.mark_command_running(command_id):
                        continue
                    payload = command["payload"]
                    try:
                        async with operation_lock:
                            result = await asyncio.to_thread(
                                self._execute_command,
                                str(command["command_type"]),
                                payload,
                                service,
                                risk,
                            )
                    except Exception as exc:
                        journal.complete_command(command_id, error=str(exc))
                        alerts.emit(
                            "OPERATOR_COMMAND_FAILED",
                            "An operator command failed",
                            symbol=payload.get("symbol"),
                            severity="CRITICAL",
                            payload={"command_id": command_id, "error": str(exc)},
                        )
                    else:
                        journal.complete_command(command_id, result=result)
                await asyncio.sleep(1)

        try:
            logger.info(
                "daemon started",
                extra={"context": {"symbols": self.symbols, "interval": self.interval}},
            )
            async with asyncio.TaskGroup() as tasks:
                tasks.create_task(user_loop())
                tasks.create_task(command_loop())
                for symbol in self.symbols:
                    tasks.create_task(market.run(symbol, self.interval))
        finally:
            logger.info("daemon stopped")
            client.close()
            journal.close()
            lock.release()

    def _execute_command(
        self,
        command_type: str,
        payload: dict[str, Any],
        service: TradingService,
        risk: RiskGovernor,
    ) -> dict[str, Any]:
        symbol = str(payload.get("symbol", "")).upper()
        if command_type == "ENTRY_INTENT":
            result = service.execute_intent(EntryIntent.from_dict(payload))
            return result.as_dict()
        if command_type == "CLOSE_POSITION":
            quantity = Decimal(payload["quantity"]) if payload.get("quantity") else None
            return service.close_position(symbol, quantity)
        if command_type == "CANCEL_ALL":
            return service.cancel_all(symbol)
        if command_type == "REPLACE_STOP":
            return service.replace_protection(symbol, "STOP_MARKET", Decimal(payload["price"]))
        if command_type == "REPLACE_TAKE_PROFIT":
            return service.replace_protection(
                symbol, "TAKE_PROFIT_MARKET", Decimal(payload["price"])
            )
        if command_type == "PROTECT_POSITION":
            return service.protect_position(
                symbol,
                stop_price=Decimal(payload["stop_price"]),
                take_profit_price=(
                    Decimal(payload["take_profit_price"])
                    if payload.get("take_profit_price")
                    else None
                ),
            )
        if command_type == "KILL_SWITCH":
            reason = str(payload.get("reason") or "operator kill switch")
            risk.lock_entries(reason)
            results: dict[str, Any] = {}
            for target in payload.get("symbols", self.symbols):
                active = [
                    item
                    for item in service.client.positions(str(target).upper())
                    if decimal_value(item.get("positionAmt", "0")) != 0
                ]
                if payload.get("close_positions") and active:
                    results[str(target).upper()] = service.close_position(str(target))
                else:
                    results[str(target).upper()] = service.cancel_all(str(target))
            return {"entryPaused": True, "results": results}
        raise ValueError(f"unknown operator command: {command_type}")
